Add error code to execution
cdit-ma/re_common pull request #20
Opened 2019-05-22 06:33 UTC by mitchell-conrad

2019-05-22 06:49 UTC, JacksonM8 requested changes

2019-05-22 06:49 UTC, JacksonM8 commented on util/execution.hpp
> +            return errors_;
Should take lock here

2019-05-22 06:49 UTC, JacksonM8 commented on util/execution.hpp
> +            if(errors_.empty()) {
Should take a lock here

2019-05-22 06:49 UTC, JacksonM8 commented on util/execution.hpp
> +        std::vector<std::string> errors_;
Could this possibly be a list of exceptions?

2019-05-22 09:39 UTC, danielrfraser reviewed
I think given that this is a more Generic class, updating the interupt function signature to look somrthing like this:

void Interupt(int return_code = 0){
   if(return_code != 0){
    return_status = return_code;
 }
}
re_node_manager already prints the errors, and this would be a far cleaner way of dealing with the errors?

2019-05-23 04:29 UTC, JacksonM8 requested changes

2019-05-23 04:29 UTC, JacksonM8 commented on util/execution.hpp
> +#include <numeric>
```suggestion
```

2019-05-23 04:29 UTC, JacksonM8 commented on util/execution.hpp
> +    void SetError(std::unique_ptr<std::exception> error)
```suggestion
    void AddException(std::unique_ptr<std::exception> error)
```

2019-05-23 04:58 UTC, merged